using System.Collections.Generic;
using System.Text;

/// <summary>English 키 → 繁體/簡體 중국어 조회.</summary>
public static class GameLocalizationChineseLookup
{
    struct Entry { public string Tw; public string Cn; }
    static readonly Dictionary<string, Entry> Map = new Dictionary<string, Entry>();

    static GameLocalizationChineseLookup()
    {
        Map["(Active)"] = new Entry { Tw = "(適用中)", Cn = "(適用中)" };
        Map["({0} more unique buys to lock)"] = new Entry { Tw = "({0}種類購入で固定)", Cn = "({0}种类购入で固定)" };
        Map["+1 afterimage shot (75%)"] = new Entry { Tw = "残像弾+1 (75%)", Cn = "残像弾+1 (75%)" };
        Map["+1 delayed homing shot (90%)"] = new Entry { Tw = "遅延追尾弾+1(90%)", Cn = "遅延追尾弾+1(90%)" };
        Map["+2 side shots (60%) \u00b7 afterimage persists"] = new Entry { Tw = "左右弾+2 (60%)\u00b7残像維持", Cn = "左右弾+2 (60%)\u00b7残像维持" };
        Map["+3rd arrow (70%)"] = new Entry { Tw = "3本目の矢(70%)", Cn = "3本目の矢(70%)" };
        Map["+3rd target (65%)"] = new Entry { Tw = "3体目追加(65%)", Cn = "3体目追加(65%)" };
        Map["+4th target (75%)"] = new Entry { Tw = "4体目(75%)", Cn = "4体目(75%)" };
        Map["+Permanent"] = new Entry { Tw = "+永久", Cn = "+永久" };
        Map["+{0}"] = new Entry { Tw = "+{0}", Cn = "+{0}" };
        Map[", chain explosion on kill"] = new Entry { Tw = "、撃破時連鎖爆発", Cn = "、撃破时连锁爆発" };
        Map["/s"] = new Entry { Tw = "/s", Cn = "/s" };
        Map["2 hits per target (2nd 80%)"] = new Entry { Tw = "対象ごと2発(2発目80%)", Cn = "対象ごと2発(2発目80%)" };
        Map["2 return trips"] = new Entry { Tw = "往復2回", Cn = "往复2回" };
        Map["2-wave burst (2nd 65%)"] = new Entry { Tw = "2波連続(2波目65%)", Cn = "2波连続(2波目65%)" };
        Map["2nd lightning strike (70%)"] = new Entry { Tw = "2回目落雷(70%)", Cn = "2回目落雷(70%)" };
        Map["4 corners \u00b7 range +1.0, ATK +12%"] = new Entry { Tw = "4隅 \u00b7 射程 +1.0, 攻擊力 +12%", Cn = "4隅 \u00b7 射程 +1.0, 攻击力 +12%" };
        Map["5-way arrows (outer 70%)"] = new Entry { Tw = "5方向矢(外側70%)", Cn = "5方向矢(外側70%)" };
        Map["6-way split"] = new Entry { Tw = "6方向分裂", Cn = "6方向分裂" };
        Map["70% slow chance"] = new Entry { Tw = "減速確率70%", Cn = "減速确率70%" };
        Map["Abyss Black Knight"] = new Entry { Tw = "深淵の黒騎士", Cn = "深淵の黒骑士" };
        Map["Acquired!"] = new Entry { Tw = "獲得!", Cn = "获得!" };
        Map["Activates at {0} units."] = new Entry { Tw = "{0}体から発動します。", Cn = "{0}体から発动します。" };
        Map["Afterglow 1.5s (40%)"] = new Entry { Tw = "残光1.5秒(40%)", Cn = "残光1.5秒(40%)" };
        Map["All"] = new Entry { Tw = "全部", Cn = "全部" };
        Map["All boss rewards available\nthis run have been claimed."] = new Entry { Tw = "今回のゲームで獲得可能な\n首領報酬をすべて獲得しました。", Cn = "今回のゲームで获得可能な\n首领報酬をすべて获得しました。" };
        Map["Allies on blue tiles above/below gain {0} attack speed; range shown as blue tiles."] = new Entry { Tw = "上下の青マスの味方に攻擊速度{0}を付与。範圍は青マスで表示。", Cn = "上下の青マスの味方に攻击速度{0}を付与。范围は青マスで表示。" };
        Map["Allies within {0} tile(s) left/right on the same row gain {1}buffs; range shown as red tiles."] = new Entry { Tw = "同じ行の左右{0}マスの味方に{1}強化を付与。範圍は赤マスで表示。", Cn = "同じ行の左右{0}マスの味方に{1}强化を付与。范围は赤マスで表示。" };
        Map["Anchor (row {0}, col {1}) \u00b7 1 tile above/below"] = new Entry { Tw = "基準 (行{0}, 列{1}) \u00b7 上下1マス", Cn = "基准 (行{0}, 列{1}) \u00b7 上下1マス" };
        Map["Anchor (row {0}, col {1}) \u00b7 {2} tile(s) left/right"] = new Entry { Tw = "基準 (行{0}, 列{1}) \u00b7 左右{2}マス", Cn = "基准 (行{0}, 列{1}) \u00b7 左右{2}マス" };
        Map["Apprentice Frost Mage"] = new Entry { Tw = "冰凍見習い魔導士", Cn = "冰冻見習い魔導士" };
        Map["Apprentice Pyromancer"] = new Entry { Tw = "見習い火火術師", Cn = "見習い火火术师" };
        Map["Are you sure you want to quit the game?"] = new Entry { Tw = "確定要離開遊戲嗎？", Cn = "确定要离开游戏吗？" };
        Map["APS {0}"] = new Entry { Tw = "攻速 {0}", Cn = "攻速 {0}" };
        Map["APS {0} \u2192 {1}"] = new Entry { Tw = "APS {0} \u2192 {1}", Cn = "APS {0} \u2192 {1}" };
        Map["Arcane Laser"] = new Entry { Tw = "秘術レーザー", Cn = "秘术レーザー" };
        Map["Arrow damage +15%"] = new Entry { Tw = "矢ダメージ+15%", Cn = "矢ダメージ+15%" };
        Map["ATK +{0} (total)"] = new Entry { Tw = "攻擊 +{0} (累計)", Cn = "攻击 +{0} (累计)" };
        Map["ATK {0}"] = new Entry { Tw = "攻擊力 {0}", Cn = "攻击力 {0}" };
        Map["ATK {0} \u2192 {1}"] = new Entry { Tw = "ATK {0} \u2192 {1}", Cn = "ATK {0} \u2192 {1}" };
        Map["ATK+{0}"] = new Entry { Tw = "攻擊+{0}", Cn = "攻击+{0}" };
        Map["Attack"] = new Entry { Tw = "攻擊力", Cn = "攻击力" };
        Map["Attack +10%"] = new Entry { Tw = "攻擊力 +10%", Cn = "攻击力 +10%" };
        Map["Attack +10%, special +20%"] = new Entry { Tw = "攻擊力 +10%, 特殊攻擊 +20%", Cn = "攻击力 +10%, 特殊攻击 +20%" };
        Map["Attack interval"] = new Entry { Tw = "攻擊周期", Cn = "攻击周期" };
        Map["Attack interval \u221212%"] = new Entry { Tw = "攻擊周期\u221212%", Cn = "攻击周期\u221212%" };
        Map["Attack interval \u22128%"] = new Entry { Tw = "攻擊周期\u22128%", Cn = "攻击周期\u22128%" };
        Map["Attack pattern"] = new Entry { Tw = "攻擊パターン", Cn = "攻击パターン" };
        Map["Attack Speed"] = new Entry { Tw = "攻擊速度", Cn = "攻击速度" };
        Map["Attack speed +10%"] = new Entry { Tw = "攻擊速度 +10%", Cn = "攻击速度 +10%" };
        Map["Attack speed +8%"] = new Entry { Tw = "攻擊速度 +8%", Cn = "攻击速度 +8%" };
        Map["Attack: {0} (Evolution x{1:0.00})"] = new Entry { Tw = "攻擊: {0} (進化 x{1:0.00})", Cn = "攻击: {0} (进化 x{1:0.00})" };
        Map["Aura extends 2 tiles left/right"] = new Entry { Tw = "左右2マスまで拡張", Cn = "左右2マスまで拡張" };
        Map["Auto-collect gold"] = new Entry { Tw = "ゴールド自動収集", Cn = "ゴールド自动収集" };
        Map["Awakening"] = new Entry { Tw = "覺醒", Cn = "觉醒" };
        Map["Awakening effects"] = new Entry { Tw = "覺醒効果", Cn = "觉醒効果" };
        Map["Awakening {0}"] = new Entry { Tw = "覺醒 {0}", Cn = "觉醒 {0}" };
        Map["Awk {0}  {1}"] = new Entry { Tw = "Awk {0}  {1}", Cn = "Awk {0}  {1}" };
        Map["Awk+{0}"] = new Entry { Tw = "覺醒+{0}", Cn = "觉醒+{0}" };
        Map["Back \u00b7 leftmost column (col 1)"] = new Entry { Tw = "後列 \u00b7 最左列全体 (列1)", Cn = "后列 \u00b7 最左列全体 (列1)" };
        Map["Backline Scope"] = new Entry { Tw = "後列望遠", Cn = "后列望远" };
        Map["Balanced"] = new Entry { Tw = "バランス", Cn = "バランス" };
        Map["Balanced mix of special roles. Only enemies allowed in the current phase."] = new Entry { Tw = "特殊モブ役割の均等混合。現区間で許可された敵のみ登場。", Cn = "特殊モブ役割の均等混合。现区间で許可された敌のみ登场。" };
        Map["Balanced Party"] = new Entry { Tw = "バランス隊伍", Cn = "バランス隊伍" };
        Map["Baron Wings"] = new Entry { Tw = "ウィングス男爵", Cn = "ウィングス男爵" };
        Map["Battle Damage"] = new Entry { Tw = "戦闘ダメージ", Cn = "戦闘ダメージ" };
        Map["Battle Result"] = new Entry { Tw = "戰鬥結果", Cn = "战斗结果" };
        Map["Beam 3.5s"] = new Entry { Tw = "ビーム3.5秒", Cn = "ビーム3.5秒" };
        Map["BGM Volume"] = new Entry { Tw = "BGM 音量", Cn = "BGM 音量" };
        Map["Blue Goblin"] = new Entry { Tw = "青鬼怪", Cn = "青鬼怪" };
        Map["Board and bench are full \u2014 cannot acquire unit."] = new Entry { Tw = "配置欄と等待欄がいっぱいで單位を獲得できません", Cn = "配置栏と等待栏がいっぱいで单位を获得できません" };
        Map["Board full \u2014 unit placed on the bench."] = new Entry { Tw = "配置欄がいっぱいのため等待欄に配置しました", Cn = "配置栏がいっぱいのため等待栏に配置しました" };
        Map["Board tile"] = new Entry { Tw = "配置マス", Cn = "配置マス" };
        Map["Boss"] = new Entry { Tw = "首領", Cn = "首领" };
        Map["Boss Appears!"] = new Entry { Tw = "首領出現！", Cn = "首领出现！" };
        Map["Boss Defeat Reward"] = new Entry { Tw = "首領撃破報酬", Cn = "首领撃破報酬" };
        Map["Boss Defeated!"] = new Entry { Tw = "首領撃破！", Cn = "首领撃破！" };
        Map["Boss Party"] = new Entry { Tw = "首領隊伍", Cn = "首领隊伍" };
        Map["Boss Reward"] = new Entry { Tw = "首領報酬", Cn = "首领報酬" };
        Map["Boss \u00b7 synergy \u00b7 unit effect tiles"] = new Entry { Tw = "首領 \u00b7 羈絆 \u00b7 單位効果マス", Cn = "首领 \u00b7 羈绊 \u00b7 单位効果マス" };
        Map["Bottom Mobility"] = new Entry { Tw = "下段機動", Cn = "下段機动" };
        Map["Bottom row (row {0})"] = new Entry { Tw = "下段行全体 (行{0})", Cn = "下段行全体 (行{0})" };
        Map["Bottom row \u00b7 attack speed +8%"] = new Entry { Tw = "下段 \u00b7 攻擊速度 +8%", Cn = "下段 \u00b7 攻击速度 +8%" };
        Map["Break Time"] = new Entry { Tw = "等待時間", Cn = "等待时间" };
        Map["Breakthrough"] = new Entry { Tw = "突破", Cn = "突破" };
        Map["Breakthrough Party"] = new Entry { Tw = "突破隊伍", Cn = "突破隊伍" };
        Map["Bruiser"] = new Entry { Tw = "タンク", Cn = "タンク" };
        Map["Bruiser Party"] = new Entry { Tw = "タンク隊伍", Cn = "タンク隊伍" };
        Map["Buffs allies left/right on the same row; range shown as red tiles."] = new Entry { Tw = "同じ行の左右味方に攻擊力\u00b7攻速強化。範圍は赤マス表示。", Cn = "同じ行の左右味方に攻击力\u00b7攻速强化。范围は赤マス表示。" };
        Map["Buy units from the shop\nand deploy them freely on the board."] = new Entry { Tw = "商店で單位を購入し\nボードに自由に配置してください", Cn = "商店で单位を购入し\nボードに自由に配置してください" };
        Map["Buy units from the shop\nand deploy them on the board."] = new Entry { Tw = "商店で單位を購入し\nボードに配置してください", Cn = "商店で单位を购入し\nボードに配置してください" };
        Map["Calamity"] = new Entry { Tw = "災厄", Cn = "灾厄" };
        Map["Calamity Mark"] = new Entry { Tw = "災厄の刻印", Cn = "灾厄の刻印" };
        Map["Calamity Pulse"] = new Entry { Tw = "災厄の波動", Cn = "灾厄の波动" };
        Map["Calls chain lightning {0}."] = new Entry { Tw = "敵に{0} 連鎖落雷を放つ。", Cn = "敌に{0} 连锁落雷を放つ。" };
        Map["Cannot deploy here."] = new Entry { Tw = "配置できません", Cn = "配置できません" };
        Map["Cannot move to a non-board tile."] = new Entry { Tw = "配置欄以外には移動できません", Cn = "配置栏以外には移动できません" };
        Map["Cannot purchase during combat."] = new Entry { Tw = "戦闘中は購入できません", Cn = "戦闘中は购入できません" };
        Map["Cannot refresh the shop during combat."] = new Entry { Tw = "戦闘中は商店を更新できません", Cn = "戦闘中は商店を更新できません" };
        Map["Cancel"] = new Entry { Tw = "取消", Cn = "取消" };
        Map["Center column (col {0})"] = new Entry { Tw = "中央列全体 (列{0})", Cn = "中央列全体 (列{0})" };
        Map["Center Column Amp"] = new Entry { Tw = "中央列増幅", Cn = "中央列増幅" };
        Map["Center column \u00b7 ATK +10%, special +20%"] = new Entry { Tw = "中央列 \u00b7 攻擊力 +10%, 特殊攻擊 +20%", Cn = "中央列 \u00b7 攻击力 +10%, 特殊攻击 +20%" };
        Map["Center Resonance"] = new Entry { Tw = "中央共鳴", Cn = "中央共鳴" };
        Map["Center tile (row {0}, col {1})"] = new Entry { Tw = "中央1マス (行{0}, 列{1})", Cn = "中央1マス (行{0}, 列{1})" };
        Map["Center tile \u00b7 synergy counts \u00d72"] = new Entry { Tw = "中央1マス \u00b7 羈絆2人分集計", Cn = "中央1マス \u00b7 羈绊2人分集计" };
        Map["Chain 3 targets \u00b7 60% damage"] = new Entry { Tw = "連鎖3体\u00b760%", Cn = "连锁3体\u00b760%" };
        Map["Chain Lightning"] = new Entry { Tw = "連鎖落雷", Cn = "连锁落雷" };
        Map["Chain range\u2191 \u00b7 +1 chain (max 2)"] = new Entry { Tw = "連鎖範圍\u2191\u00b7連鎖+1(最大2)", Cn = "连锁范围\u2191\u00b7连锁+1(最大2)" };
        Map["Chills an enemy {0}."] = new Entry { Tw = "敵に{0} 霜の手をかける。", Cn = "敌に{0} 霜の手をかける。" };
        Map["Chills {1} enemies {0}."] = new Entry { Tw = "敵{1}体に{0} 霜の手をかける。", Cn = "敌{1}体に{0} 霜の手をかける。" };
        Map["Choose one of three units."] = new Entry { Tw = "3体の單位から1体を選んでください", Cn = "3体の单位から1体を选んでください" };
        Map["Choose one."] = new Entry { Tw = "1つ選んでください", Cn = "1つ选んでください" };
        Map["Choose Starting Unit"] = new Entry { Tw = "開始單位選択", Cn = "开始单位选択" };
        Map["Close"] = new Entry { Tw = "關閉", Cn = "关闭" };
        Map["Codex"] = new Entry { Tw = "図鑑", Cn = "図鉴" };
        Map["Coin-Scraping Beggar"] = new Entry { Tw = "コイン拾い乞食", Cn = "コイン拾い乞食" };
        Map["Collapse"] = new Entry { Tw = "折りたたむ", Cn = "折りたたむ" };
        Map["Combat stats"] = new Entry { Tw = "戦闘能力", Cn = "戦闘能力" };
        Map["Combo punch (2nd 70%)"] = new Entry { Tw = "連続拳(2打目70%)", Cn = "连続拳(2打目70%)" };
        Map["Contact damage +15%"] = new Entry { Tw = "接触ダメージ+15%", Cn = "接触ダメージ+15%" };
        Map["Contact tick 0.85s"] = new Entry { Tw = "接触Tick0.85秒", Cn = "接触Tick0.85秒" };
        Map["Continue"] = new Entry { Tw = "繼續", Cn = "继续" };
        Map["Corner Point"] = new Entry { Tw = "コーナーポイント", Cn = "コーナーポイント" };
        Map["Count Justice"] = new Entry { Tw = "ジャスティス伯爵", Cn = "ジャスティス伯爵" };
        Map["Cowardly Hunter"] = new Entry { Tw = "臆病な狩人", Cn = "臆病な狩人" };
        Map["Creates a shadow vortex near enemies {0}."] = new Entry { Tw = "敵の周囲に{0} 影の渦を起こす。", Cn = "敌の周囲に{0} 影の渦を起こす。" };
        Map["Damages enemies on the purple pad on the right every 1s."] = new Entry { Tw = "戦場右側の紫床内の敵に1秒に1回ダメージ。", Cn = "戦场右側の紫床内の敌に1秒に1回ダメージ。" };
        Map["Dark"] = new Entry { Tw = "暗", Cn = "暗" };
        Map["Dark Elf Archer"] = new Entry { Tw = "ダークエルフ弓使い", Cn = "ダークエルフ弓使い" };
        Map["Ddujjon Goblin"] = new Entry { Tw = "豆豆鬼怪", Cn = "豆豆鬼怪" };
        Map["Demo Clear!"] = new Entry { Tw = "試玩通關！", Cn = "试玩通关！" };
        Map["Demon"] = new Entry { Tw = "デーモン", Cn = "デーモン" };
        Map["Deploy"] = new Entry { Tw = "配置", Cn = "配置" };
        Map["Deploy at least one unit on the board before starting."] = new Entry { Tw = "配置欄に單位を1体以上配置してから開始してください", Cn = "配置栏に单位を1体以上配置してから开始してください" };
        Map["Deploy on board once"] = new Entry { Tw = "ボード配置が1回必要", Cn = "ボード配置が1回必要" };
        Map["Deploy Units \u00b7 Use Shop"] = new Entry { Tw = "部署單位 \u00b7 使用商店", Cn = "部署单位 \u00b7 使用商店" };
        Map["Display"] = new Entry { Tw = "畫面 / 顯示", Cn = "画面 / 显示" };
        Map["Does not auto-attack; boosts ally attack speed on blue tiles above/below."] = new Entry { Tw = "自動攻擊なし。上下の青マスの味方攻速UP。", Cn = "自动攻击なし。上下の青マスの味方攻速UP。" };
        Map["Double tap (2nd 80%)"] = new Entry { Tw = "ダブルタップ(2発目80%)", Cn = "ダブルタップ(2発目80%)" };
        Map["Drops {1} fireballs and embers near enemies {0}."] = new Entry { Tw = "敵の周囲に{0} 火球{1}発と残火を落とす。", Cn = "敌の周囲に{0} 火球{1}発と残火を落とす。" };
        Map["Drops {1} fireballs near enemies {0}."] = new Entry { Tw = "敵の周囲に{0} 火球{1}発を落とす。", Cn = "敌の周囲に{0} 火球{1}発を落とす。" };
        Map["Duke Candy"] = new Entry { Tw = "キャンディ公爵", Cn = "キャンディ公爵" };
        Map["Encounter in battle to unlock."] = new Entry { Tw = "戦闘で出会うと記録されます", Cn = "戦闘で出会うと記録されます" };
        Map["End explosion (80%)"] = new Entry { Tw = "終了爆発(80%)", Cn = "終了爆発(80%)" };
        Map["End splash (50%)"] = new Entry { Tw = "終了時残スプラッシュ(50%)", Cn = "終了时残スプラッシュ(50%)" };
        Map["Enemies Defeated"] = new Entry { Tw = "撃破数", Cn = "撃破数" };
        Map["Enemies on the purple pad on the right take damage {0}."] = new Entry { Tw = "戦場右側の紫床内の敵に{0}ダメージ。", Cn = "戦场右側の紫床内の敌に{0}ダメージ。" };
        Map["Enemies rush in as soon as the round starts!"] = new Entry { Tw = "開始と同時に敵が押し寄せます！", Cn = "开始と同时に敌が押し寄せます！" };
        Map["Enemy HP Boost"] = new Entry { Tw = "敵HP強化", Cn = "敌HP强化" };
        Map["Entire Battlefield"] = new Entry { Tw = "戦場全域", Cn = "戦场全域" };
        Map["Even larger \u00b7 tick 0.85s"] = new Entry { Tw = "さらに拡大\u00b7Tick0.85秒", Cn = "さらに拡大\u00b7Tick0.85秒" };
        Map["Every 10s, places a freeze pad on a random column."] = new Entry { Tw = "10秒に1回ランダム列に冰凍床を設置。", Cn = "10秒に1回ランダム列に冰冻床を设置。" };
        Map["Every 16s, attacks in a straight line from the right column."] = new Entry { Tw = "16秒に1回、戦場右列から直線攻擊。", Cn = "16秒に1回、戦场右列から直线攻击。" };
        Map["Every 2s, bounces attacks between the two nearest enemies."] = new Entry { Tw = "最も近い2体に2秒に1回跳弾攻擊。", Cn = "最も近い2体に2秒に1回跳弾攻击。" };
        Map["Every 3s, fires a straight shot that splits on hit."] = new Entry { Tw = "3秒に1回直線弾。命中時に分裂。", Cn = "3秒に1回直线弾。命中时に分裂。" };
        Map["Every 3s, fires three arrows based on the nearest enemy."] = new Entry { Tw = "最も近い敵基準で3秒に1回3方向の矢。", Cn = "最も近い敌基准で3秒に1回3方向の矢。" };
        Map["Every 4s, roots a random location for damage."] = new Entry { Tw = "4秒に1回ランダム位置に根の床で攻擊。", Cn = "4秒に1回ランダム位置に根の床で攻击。" };
        Map["Evolution 1 Preview"] = new Entry { Tw = "1進化プレビュー", Cn = "1进化プレビュー" };
        Map["Evolution effect"] = new Entry { Tw = "進化効果", Cn = "进化効果" };
        Map["Evolution traits"] = new Entry { Tw = "進化特性", Cn = "进化特性" };
        Map["Evolution traits (4\u00b76\u00b79)"] = new Entry { Tw = "進化特性 (4\u00b76\u00b79)", Cn = "进化特性 (4\u00b76\u00b79)" };
        Map["Evolution traits (unlock)"] = new Entry { Tw = "進化特性 (解放)", Cn = "进化特性 (解放)" };
        Map["Evolution traits \u25b6 Boost!"] = new Entry { Tw = "進化特性 \u25b6 強化!", Cn = "进化特性 \u25b6 强化!" };
        Map["Evolve"] = new Entry { Tw = "進化", Cn = "进化" };
        Map["Evolve \u25b2"] = new Entry { Tw = "進化 \u25b2", Cn = "进化 \u25b2" };
        Map["Experience"] = new Entry { Tw = "經驗值", Cn = "经验值" };
        Map["Fast breakthrough specials. After R21, types 8\u00b79 (ultra-fast, revive) appear."] = new Entry { Tw = "高速突破特殊モブ中心。21R以降8\u00b79番（超高速・復活）登場。", Cn = "高速突破特殊モブ中心。21R以降8\u00b79番（超高速・复活）登场。" };
        Map["Favorite"] = new Entry { Tw = "お気に入り", Cn = "お気に入り" };
        Map["Fire"] = new Entry { Tw = "火", Cn = "火" };
        Map["Fires a holy beam at the farthest enemy {0}."] = new Entry { Tw = "最も遠い敵に{0} 聖光ビームを放つ。", Cn = "最も远い敌に{0} 圣光ビームを放つ。" };
        Map["Fires a laser at the nearest enemy every 7s."] = new Entry { Tw = "最も近い敵に7秒に1回レーザー。", Cn = "最も近い敌に7秒に1回レーザー。" };
        Map["Fires a laser beam at the nearest enemy every 5s."] = new Entry { Tw = "最も近い敵に5秒に1回レーザービーム。", Cn = "最も近い敌に5秒に1回レーザービーム。" };
        Map["Fires a piercing shot every 5s."] = new Entry { Tw = "5秒に1回貫通弾を発射。", Cn = "5秒に1回貫通弾を発射。" };
        Map["Fires a reflective projectile every 3s."] = new Entry { Tw = "3秒に1回反射投射体を発射。", Cn = "3秒に1回反射投射体を発射。" };
        Map["Fires a ricochet ball every 5s."] = new Entry { Tw = "5秒に1回反射ボールを発射。", Cn = "5秒に1回反射ボールを発射。" };
        Map["Fires an arcane laser at the nearest enemy {0}."] = new Entry { Tw = "最も近い敵に{0} 秘術レーザーを放つ。", Cn = "最も近い敌に{0} 秘术レーザーを放つ。" };
        Map["Fires an electric shot at the nearest enemy every 3.3s."] = new Entry { Tw = "最も近い敵に3.3秒に1回電気弾を発射。", Cn = "最も近い敌に3.3秒に1回电気弾を発射。" };
        Map["Fires an ice shard at the nearest enemy {0}."] = new Entry { Tw = "最も近い敵に{0} 冰河の棘を放つ。", Cn = "最も近い敌に{0} 冰河の棘を放つ。" };
        Map["Fires guardian arrows at {1} nearby enemies {0}."] = new Entry { Tw = "近くの敵{1}体に{0} 守護の矢を放つ。", Cn = "近くの敌{1}体に{0} 守护の矢を放つ。" };
        Map["Fires homing shots at {1} nearby enemies {0}."] = new Entry { Tw = "近くの敵{1}体に{0} 誘導弾を放つ。", Cn = "近くの敌{1}体に{0} 誘導弾を放つ。" };
        Map["Fires ice at the nearest enemy every 3.3s; may slow on hit."] = new Entry { Tw = "最も近い敵に3.3秒に1回冰弾。確率で減速。", Cn = "最も近い敌に3.3秒に1回冰弾。确率で減速。" };
        Map["Fires lasers at the three nearest enemies every 5s."] = new Entry { Tw = "最も近い3体に5秒に1回レーザー。", Cn = "最も近い3体に5秒に1回レーザー。" };
        Map["Fires stun arrows at the two nearest enemies every 8s."] = new Entry { Tw = "最も近い2体に8秒に1回暈眩矢。", Cn = "最も近い2体に8秒に1回暈眩矢。" };
        Map["Fires {1} gusts forward {0}."] = new Entry { Tw = "前方に{0} 突風{1}発を放つ。", Cn = "前方に{0} 突风{1}発を放つ。" };
        Map["First meet ({0} units)"] = new Entry { Tw = "初遭遇 ({0}体)", Cn = "初遭遇 ({0}体)" };
        Map["Forest Spirit"] = new Entry { Tw = "森の精霊", Cn = "森の精霊" };
        Map["Forest Witch"] = new Entry { Tw = "森の魔女", Cn = "森の魔女" };
        Map["Four corner tiles"] = new Entry { Tw = "四隅マス", Cn = "四隅マス" };
        Map["Freeze 2.5s"] = new Entry { Tw = "冰凍2.5秒", Cn = "冰冻2.5秒" };
        Map["Front \u00b7 rightmost column (col {0})"] = new Entry { Tw = "前線 \u00b7 最右列全体 (列{0})", Cn = "前线 \u00b7 最右列全体 (列{0})" };
        Map["Frontline Break"] = new Entry { Tw = "前線突破", Cn = "前线突破" };
        Map["Frost Assassin"] = new Entry { Tw = "霜暗殺者", Cn = "霜暗殺者" };
        Map["Frost Touch"] = new Entry { Tw = "霜の手", Cn = "霜の手" };
        Map["Fullscreen"] = new Entry { Tw = "全螢幕", Cn = "全屏" };
        Map["Gale Warlock"] = new Entry { Tw = "疾風魔導士", Cn = "疾风魔導士" };
        Map["Glacial Shard"] = new Entry { Tw = "冰河の棘", Cn = "冰河の棘" };
        Map["Goblin"] = new Entry { Tw = "鬼怪", Cn = "鬼怪" };
        Map["Goblin Homing Shot"] = new Entry { Tw = "鬼怪誘導弾", Cn = "鬼怪誘導弾" };
        Map["Goblin King"] = new Entry { Tw = "ゴブリンキング", Cn = "ゴブリンキング" };
        Map["Gold"] = new Entry { Tw = "ゴールド", Cn = "ゴールド" };
        Map["Gold CD \u2212{0:0.#}% \u2192 \u2212{1:0.#}%"] = new Entry { Tw = "金幣 CD \u2212{0:0.#}% \u2192 \u2212{1:0.#}%", Cn = "金幣 CD \u2212{0:0.#}% \u2192 \u2212{1:0.#}%" };
        Map["Gold gain +2 (total 3)"] = new Entry { Tw = "ゴールド+2(合計3)", Cn = "ゴールド+2(合计3)" };
        Map["Gold Held"] = new Entry { Tw = "所持ゴールド", Cn = "所持ゴールド" };
        Map["Gold spawn 4s \u2192 3.5s"] = new Entry { Tw = "ゴールド生成4秒\u21923.5秒", Cn = "ゴールド生成4秒\u21923.5秒" };
        Map["Gold \u2212{0:0.#}%"] = new Entry { Tw = "ゴールド\u2212{0:0.#}%", Cn = "ゴールド\u2212{0:0.#}%" };
        Map["Golden Knight"] = new Entry { Tw = "黄金騎士", Cn = "黄金骑士" };
        Map["Grade 1 {0}. An elite unit with top-tier combat ability."] = new Entry { Tw = "1級 {0}. 最高級の戦闘能力を持つエリート單位。", Cn = "1级 {0}. 最高级の戦闘能力を持つエリート单位。" };
        Map["Grade 2 {0}. A unit with very strong combat ability."] = new Entry { Tw = "2級 {0}. 非常に強力な戦闘能力を持つ單位。", Cn = "2级 {0}. 非常に强力な戦闘能力を持つ单位。" };
        Map["Grade 3 {0}. A unit with strong combat ability."] = new Entry { Tw = "3級 {0}. 強力な戦闘能力を誇る單位。", Cn = "3级 {0}. 强力な戦闘能力を誇る单位。" };
        Map["Grade 4 {0}. A unit with improved combat ability."] = new Entry { Tw = "4級 {0}. 強化された戦闘能力を持つ單位。", Cn = "4级 {0}. 强化された戦闘能力を持つ单位。" };
        Map["Grade 5 {0}. A unit with basic combat ability."] = new Entry { Tw = "5級 {0}. 基本的な戦闘能力を持つ單位。", Cn = "5级 {0}. 基本的な戦闘能力を持つ单位。" };
        Map["Grade Odds"] = new Entry { Tw = "級確率", Cn = "级确率" };
        Map["Grade {0}"] = new Entry { Tw = "級{0}", Cn = "级{0}" };
        Map["Grade {0} shop pool locked \u2014 {1}"] = new Entry { Tw = "級{0}商店プール固定 \u2014 {1}", Cn = "级{0}商店プール固定 \u2014 {1}" };
        Map["Grade {0} unit"] = new Entry { Tw = "{0}級單位", Cn = "{0}级单位" };
        Map["Grade {0} {1} \u2014 review encounter records, evolution, and awakening info."] = new Entry { Tw = "{0}級 {1} \u2014 遭遇記録と進化・覺醒情報を確認できます。", Cn = "{0}级 {1} \u2014 遭遇記録と进化・觉醒情報を确认できます。" };
        Map["Guardian Arrow"] = new Entry { Tw = "守護の矢", Cn = "守护の矢" };
        Map["Gust"] = new Entry { Tw = "突風", Cn = "突风" };
        Map["Gust field 3.5s"] = new Entry { Tw = "突風3.5秒", Cn = "突风3.5秒" };
        Map["Hand of Execution"] = new Entry { Tw = "処刑の手", Cn = "処刑の手" };
        Map["Higher ATK/APS aura"] = new Entry { Tw = "攻擊力\u00b7攻速強化UP", Cn = "攻击力\u00b7攻速强化UP" };
        Map["Hitbox +15%"] = new Entry { Tw = "ヒット判定+15%", Cn = "ヒット判定+15%" };
        Map["Holy Light"] = new Entry { Tw = "聖光", Cn = "圣光" };
        Map["Homing +20% \u00b7 interval \u22128%"] = new Entry { Tw = "追尾+20%\u00b7周期\u22128%", Cn = "追尾+20%\u00b7周期\u22128%" };
        Map["Homing acceleration"] = new Entry { Tw = "追尾加速", Cn = "追尾加速" };
        Map["Homing after 3 roams"] = new Entry { Tw = "3回ローミング後追尾", Cn = "3回ローミング后追尾" };
        Map["HP"] = new Entry { Tw = "HP", Cn = "HP" };
        Map["Ice"] = new Entry { Tw = "冰", Cn = "冰" };
        Map["Interval \u221210% \u00b7 +1 bounce"] = new Entry { Tw = "周期\u221210%\u00b7跳弾+1", Cn = "周期\u221210%\u00b7跳弾+1" };
        Map["Interval \u221210% \u00b7 +50% slow bonus shot"] = new Entry { Tw = "周期\u221210%\u00b7減速時追加弾50%", Cn = "周期\u221210%\u00b7減速时追加弾50%" };
        Map["Interval \u221210% \u00b7 chain damage 100%"] = new Entry { Tw = "周期\u221210%\u00b7連鎖100%", Cn = "周期\u221210%\u00b7连锁100%" };
        Map["Knockback +15%"] = new Entry { Tw = "ノックバック+15%", Cn = "ノックバック+15%" };
        Map["Lance Wave"] = new Entry { Tw = "槍術波動", Cn = "槍术波动" };
        Map["Language"] = new Entry { Tw = "語言", Cn = "语言" };
        Map["Larger pad \u00b7 tick +20%"] = new Entry { Tw = "床拡大\u00b7Tick+20%", Cn = "床拡大\u00b7Tick+20%" };
        Map["Laser 3.5s"] = new Entry { Tw = "レーザー3.5秒", Cn = "レーザー3.5秒" };
        Map["Laser lasts 3.5s"] = new Entry { Tw = "レーザー3.5秒", Cn = "レーザー3.5秒" };
        Map["Lashes {1} enemies with vines {0}."] = new Entry { Tw = "敵{1}体に{0} ツタを振る。", Cn = "敌{1}体に{0} ツタを振る。" };
        Map["Launches a lance wave forward {0}."] = new Entry { Tw = "前方に{0} 槍術波動を放つ。", Cn = "前方に{0} 槍术波动を放つ。" };
        Map["Left column \u00b7 range +1.5"] = new Entry { Tw = "左列 \u00b7 射程 +1.5", Cn = "左列 \u00b7 射程 +1.5" };
        Map["Level Reached"] = new Entry { Tw = "到達等級", Cn = "到達等级" };
        Map["Level {0}"] = new Entry { Tw = "等級 {0}", Cn = "等级 {0}" };
        Map["Level {0} Reached!"] = new Entry { Tw = "等級{0}達成！", Cn = "等级{0}達成！" };
        Map["Light"] = new Entry { Tw = "光", Cn = "光" };
        Map["Lightning"] = new Entry { Tw = "雷", Cn = "雷" };
        Map["Linger 2.5s"] = new Entry { Tw = "滞留2.5秒", Cn = "滞留2.5秒" };
        Map["Lingering aura 1.5s (50% dmg)"] = new Entry { Tw = "残留オーラ1.5秒(50%ダメージ)", Cn = "残留オーラ1.5秒(50%ダメージ)" };
        Map["Lingering freeze 1.2s \u00b7 interval \u221210%"] = new Entry { Tw = "残冰凍1.2秒\u00b7周期\u221210%", Cn = "残冰冻1.2秒\u00b7周期\u221210%" };
        Map["Lost Ghost"] = new Entry { Tw = "道迷い幽霊", Cn = "道迷い幽霊" };
        Map["Lv{0}/{1}"] = new Entry { Tw = "Lv{0}/{1}", Cn = "Lv{0}/{1}" };
        Map["Mage"] = new Entry { Tw = "法師", Cn = "法师" };
        Map["Main shot double (2nd 75%)"] = new Entry { Tw = "本体弾2連(2発目75%)", Cn = "本体弾2连(2発目75%)" };
        Map["Many swarm special enemies. Reinforcements make this the largest wave."] = new Entry { Tw = "物量型特殊モブ多数。雑魚増援と重なり敵数が最多。", Cn = "物量型特殊モブ多数。雑鱼増援と重なり敌数が最多。" };
        Map["Marks {1} nearby enemies {0} (+{2}% damage taken{3})."] = new Entry { Tw = "近くの敵{1}体に{0} 刻印を付与(刻印対象ダメージ+{2}%{3})。", Cn = "近くの敌{1}体に{0} 刻印を付与(刻印対象ダメージ+{2}%{3})。" };
        Map["Master Volume"] = new Entry { Tw = "主音量", Cn = "主音量" };
        Map["Max pad \u00b7 move speed \u221215%"] = new Entry { Tw = "最大床\u00b7移動\u221215%", Cn = "最大床\u00b7移动\u221215%" };
        Map["Max top/bottom tile APS buff"] = new Entry { Tw = "上下マス攻速最大", Cn = "上下マス攻速最大" };
        Map["Medals Earned"] = new Entry { Tw = "獲得勲章", Cn = "获得勲章" };
        Map["Medals {0}"] = new Entry { Tw = "勲章 {0}", Cn = "勲章 {0}" };
        Map["Mercenary Archive"] = new Entry { Tw = "傭兵檔案", Cn = "佣兵档案" };
        Map["Meteor Fall"] = new Entry { Tw = "火火落下", Cn = "火火落下" };
        Map["Milestone"] = new Entry { Tw = "マイルストーン", Cn = "マイルストーン" };
        Map["Milestone (R10+)"] = new Entry { Tw = "マイルストーン (10R+)", Cn = "マイルストーン (10R+)" };
        Map["Milestone (R10\u00b720+)"] = new Entry { Tw = "マイルストーン (10\u00b720R+)", Cn = "マイルストーン (10\u00b720R+)" };
        Map["Milestone (R10\u00b720\u00b730+)"] = new Entry { Tw = "マイルストーン (10\u00b720\u00b730R+)", Cn = "マイルストーン (10\u00b720\u00b730R+)" };
        Map["Mischief Goblin"] = new Entry { Tw = "いたずら鬼怪", Cn = "いたずら鬼怪" };
        Map["Mob \u2212{0:0.#}%"] = new Entry { Tw = "Mob \u2212{0:0.#}%", Cn = "Mob \u2212{0:0.#}%" };
        Map["Mobility"] = new Entry { Tw = "機動", Cn = "機动" };
        Map["N/A"] = new Entry { Tw = "N/A", Cn = "N/A" };
        Map["Nature"] = new Entry { Tw = "自然", Cn = "自然" };
        Map["Need 3+ permanent upgrade levels"] = new Entry { Tw = "永久強化3以上が必要", Cn = "永久强化3以上が必要" };
        Map["Need lifetime 5-star evolution"] = new Entry { Tw = "5進化達成(累計)が必要", Cn = "5进化達成(累计)が必要" };
        Map["Next Round  \u25b6"] = new Entry { Tw = "下一回合  \u25b6", Cn = "下一回合  \u25b6" };
        Map["No active synergy, boss, or unit tile effects."] = new Entry { Tw = "適用中の羈絆\u00b7首領\u00b7單位効果はありません。", Cn = "適用中の羈绊\u00b7首领\u00b7单位効果はありません。" };
        Map["No pattern info"] = new Entry { Tw = "パターン情報なし", Cn = "パターン情報なし" };
        Map["No registered units yet."] = new Entry { Tw = "登録された單位がまだありません", Cn = "登録された单位がまだありません" };
        Map["None"] = new Entry { Tw = "無", Cn = "无" };
        Map["Normal Combat"] = new Entry { Tw = "一般戰鬥", Cn = "一般战斗" };
        Map["Not active yet"] = new Entry { Tw = "まだ発動していません", Cn = "まだ発动していません" };
        Map["Not enough gold! ({0} gold required)"] = new Entry { Tw = "ゴールドが足りません！（{0}ゴールド必要）", Cn = "ゴールドが足りません！（{0}ゴールド必要）" };
        Map["Notice"] = new Entry { Tw = "通知", Cn = "通知" };
        Map["OK"] = new Entry { Tw = "確認", Cn = "确认" };
        Map["once every {0:0.##}s"] = new Entry { Tw = "{0:0.##}秒に1回", Cn = "{0:0.##}秒に1回" };
        Map["once every {0}s"] = new Entry { Tw = "{0}秒に1回", Cn = "{0}秒に1回" };
        Map["once every {0}s ({1}% chance)"] = new Entry { Tw = "{0}秒に1回({1}%確率)", Cn = "{0}秒に1回({1}%确率)" };
        Map["One boss plus phase escorts. Boss stages at R10, R20, R30."] = new Entry { Tw = "首領1体＋区間別特殊モブ護衛。10R\u00b720R\u00b730R首領段階。", Cn = "首领1体＋区间別特殊モブ护卫。10R\u00b720R\u00b730R首领段階。" };
        Map["Order"] = new Entry { Tw = "騎士團", Cn = "骑士团" };
        Map["Owned Unit Pool"] = new Entry { Tw = "所持單位プール", Cn = "所持单位プール" };
        Map["Owned {0}"] = new Entry { Tw = "所持 {0}", Cn = "所持 {0}" };
        Map["Pad damage 40%"] = new Entry { Tw = "床ダメージ40%", Cn = "床ダメージ40%" };
        Map["Pad duration +35%"] = new Entry { Tw = "床持続+35%", Cn = "床持続+35%" };
        Map["Pad width +25%"] = new Entry { Tw = "床幅+25%", Cn = "床幅+25%" };
        Map["Party"] = new Entry { Tw = "隊伍", Cn = "隊伍" };
        Map["Party Bonus Alerts"] = new Entry { Tw = "隊伍加成提示", Cn = "队伍加成提示" };
        Map["Party Incoming"] = new Entry { Tw = "隊伍出現", Cn = "隊伍出现" };
        Map["Pattern"] = new Entry { Tw = "パターン", Cn = "パターン" };
        Map["Pattern:"] = new Entry { Tw = "パターン:", Cn = "パターン:" };
        Map["Paused"] = new Entry { Tw = "暫停", Cn = "暂停" };
        Map["Penguin"] = new Entry { Tw = "企鵝", Cn = "企鹅" };
        Map["Penguin Adjacent Aura"] = new Entry { Tw = "企鵝隣接オーラ", Cn = "企鹅隣接オーラ" };
        Map["Permanent evolution pattern boost"] = new Entry { Tw = "進化パターン永久補正", Cn = "进化パターン永久補正" };
        Map["Permanent Upgrades"] = new Entry { Tw = "永久強化", Cn = "永久强化" };
        Map["Pierce damage 35%"] = new Entry { Tw = "貫通ダメージ35%", Cn = "貫通ダメージ35%" };
        Map["Piercing Red Knight"] = new Entry { Tw = "貫通の赤騎士", Cn = "貫通の赤骑士" };
        Map["Places a gust field on the nearest enemy every 7s."] = new Entry { Tw = "7秒に1回最も近い敵位置に突風フィールド。", Cn = "7秒に1回最も近い敌位置に突风フィールド。" };
        Map["Places a vortex on a distant enemy every 10s."] = new Entry { Tw = "10秒に1回遠い敵位置に渦を設置。", Cn = "10秒に1回远い敌位置に渦を设置。" };
        Map["Play Again"] = new Entry { Tw = "再玩一次", Cn = "再玩一次" };
        Map["Pool Locked"] = new Entry { Tw = "プール固定", Cn = "プール固定" };
        Map["Pool {0}/{1}"] = new Entry { Tw = "プール {0}/{1}", Cn = "プール {0}/{1}" };
        Map["Precision White Knight"] = new Entry { Tw = "精密の白騎士", Cn = "精密の白骑士" };
        Map["Pull +20%"] = new Entry { Tw = "引き寄せ+20%", Cn = "引き寄せ+20%" };
        Map["Punches enemy positions every 5s."] = new Entry { Tw = "5秒に1回敵位置に拳攻擊。", Cn = "5秒に1回敌位置に拳攻击。" };
        Map["Quit"] = new Entry { Tw = "離開", Cn = "离开" };
        Map["Quit Game"] = new Entry { Tw = "離開遊戲", Cn = "离开游戏" };
        Map["Radius +20%"] = new Entry { Tw = "半径+20%", Cn = "半径+20%" };
        Map["Radius 1.6 \u2192 1.8"] = new Entry { Tw = "半徑 1.6 \u2192 1.8", Cn = "半徑 1.6 \u2192 1.8" };
        Map["Range"] = new Entry { Tw = "射程", Cn = "射程" };
        Map["Range +1.0, ATK +12%"] = new Entry { Tw = "射程 +1.0, 攻擊力 +12%", Cn = "射程 +1.0, 攻击力 +12%" };
        Map["Range +1.5"] = new Entry { Tw = "射程 +1.5", Cn = "射程 +1.5" };
        Map["Range {0:0.#} \u2192 {1:0.#}"] = new Entry { Tw = "射程 {0:0.#} \u2192 {1:0.#}", Cn = "射程 {0:0.#} \u2192 {1:0.#}" };
        Map["Range+{0:0.#}"] = new Entry { Tw = "射程+{0:0.#}", Cn = "射程+{0:0.#}" };
        Map["Range: {0:0.#}"] = new Entry { Tw = "射程: {0:0.#}", Cn = "射程: {0:0.#}" };
        Map["Range: {0}"] = new Entry { Tw = "射程: {0}", Cn = "射程: {0}" };
        Map["Ranged"] = new Entry { Tw = "遠距離", Cn = "远距离" };
        Map["Ranged Party"] = new Entry { Tw = "遠距離隊伍", Cn = "远距离隊伍" };
        Map["Ranged specials (2\u00b76) plus tank front. Types 6\u00b77 added from R11."] = new Entry { Tw = "遠距離(2\u00b76)特殊モブ火力＋タンク前衛。11Rから6\u00b77番追加。", Cn = "远距离(2\u00b76)特殊モブ火力＋タンク前卫。11Rから6\u00b77番追加。" };
        Map["Ravenous Ghoul"] = new Entry { Tw = "貪るグール", Cn = "貪るグール" };
        Map["Reach 3-star evolution"] = new Entry { Tw = "3進化が必要", Cn = "3进化が必要" };
        Map["Reach 5-star evolution"] = new Entry { Tw = "5進化が必要", Cn = "5进化が必要" };
        Map["Recorded \u00b7 upgrades locked"] = new Entry { Tw = "記録済 \u00b7 強化ロック", Cn = "記録済 \u00b7 强化ロック" };
        Map["Red Goblin"] = new Entry { Tw = "赤鬼怪", Cn = "赤鬼怪" };
        Map["Reflect lifetime +25%"] = new Entry { Tw = "反射寿命+25%", Cn = "反射寿命+25%" };
        Map["Refresh"] = new Entry { Tw = "更新", Cn = "更新" };
        Map["Registered Pool"] = new Entry { Tw = "登録プール", Cn = "登録プール" };
        Map["Reroll Cards (1x)"] = new Entry { Tw = "カード再選択 (1回)", Cn = "カード再选択 (1回)" };
        Map["Reroll Used"] = new Entry { Tw = "已重抽", Cn = "已重抽" };
        Map["Restart"] = new Entry { Tw = "重新開始", Cn = "重新开始" };
        Map["Right battlefield barrier (purple pad)"] = new Entry { Tw = "戦場右側防禦壁 (紫床)", Cn = "戦场右側防禦壁 (紫床)" };
        Map["Right column \u00b7 attack speed +10%"] = new Entry { Tw = "右列 \u00b7 攻擊速度 +10%", Cn = "右列 \u00b7 攻击速度 +10%" };
        Map["Rogue"] = new Entry { Tw = "盜賊團", Cn = "盗贼团" };
        Map["Round ({0}\u00d72)"] = new Entry { Tw = "回合 ({0}\u00d72)", Cn = "回合 ({0}\u00d72)" };
        Map["Round 1 Prep"] = new Entry { Tw = "第 1 回合準備", Cn = "第 1 回合准备" };
        Map["Round Reached"] = new Entry { Tw = "到達回合", Cn = "到達回合" };
        Map["ROUND {0}"] = new Entry { Tw = "ROUND {0}", Cn = "ROUND {0}" };
        Map["Round {0}  <color=#FFC94D>{1}</color>"] = new Entry { Tw = "第 {0} 回合  <color=#FFC94D>{1}</color>", Cn = "第 {0} 回合  <color=#FFC94D>{1}</color>" };
        Map["Round {0} \u2014 Enemy HP \u00d7{1:0.##} (Total \u00d7{2:0.##})"] = new Entry { Tw = "第 {0} 回合 \u2014 敵人 HP \u00d7{1:0.##} (總計 \u00d7{2:0.##})", Cn = "第 {0} 回合 \u2014 敌人 HP \u00d7{1:0.##} (总计 \u00d7{2:0.##})" };
        Map["R{0} \u00b7 Total {1:N0}"] = new Entry { Tw = "R{0} \u00b7 總計 {1:N0}", Cn = "R{0} \u00b7 总计 {1:N0}" };
        Map["s"] = new Entry { Tw = "s", Cn = "s" };
        Map["Secondary blast (70%)"] = new Entry { Tw = "2次爆発 (70%)", Cn = "2次爆発 (70%)" };
        Map["Select your first unit."] = new Entry { Tw = "最初の單位を1体選んでください", Cn = "最初の单位を1体选んでください" };
        Map["Settings"] = new Entry { Tw = "設定", Cn = "设置" };
        Map["Shadow Vortex"] = new Entry { Tw = "影の渦", Cn = "影の渦" };
        Map["Shadowless Rogue"] = new Entry { Tw = "無影刺客", Cn = "无影刺客" };
        Map["Shuriken Barrage"] = new Entry { Tw = "手裏剣連撃", Cn = "手裏剣连撃" };
        Map["Slow 65% \u00b7 2.5s"] = new Entry { Tw = "減速65%\u00b72.5秒", Cn = "減速65%\u00b72.5秒" };
        Map["Sound"] = new Entry { Tw = "音效", Cn = "音效" };
        Map["Spawns a gold icon every 4s; click to collect gold."] = new Entry { Tw = "4秒に1回ゴールドアイコン生成。クリックで獲得。", Cn = "4秒に1回ゴールドアイコン生成。クリックで获得。" };
        Map["Special Skills"] = new Entry { Tw = "特殊スキル", Cn = "特殊スキル" };
        Map["Specials: {0} + constant minion reinforcements\n{1}"] = new Entry { Tw = "特殊モブ: {0}体 + 雑魚常時増援\n{1}", Cn = "特殊モブ: {0}体 + 雑鱼常时増援\n{1}" };
        Map["Splash 3.0 \u2192 3.5"] = new Entry { Tw = "スプラッシュ3.0\u21923.5", Cn = "スプラッシュ3.0\u21923.5" };
        Map["Stage-2 vortex (65%)"] = new Entry { Tw = "2段階渦(65%)", Cn = "2段階渦(65%)" };
        Map["Star Goblin"] = new Entry { Tw = "星の鬼怪", Cn = "星の鬼怪" };
        Map["Start Game"] = new Entry { Tw = "開始遊戲", Cn = "开始游戏" };
        Map["Start Round 1  \u25b6"] = new Entry { Tw = "開始第 1 回合  \u25b6", Cn = "开始第 1 回合  \u25b6" };
        Map["Strike radius 1.2 \u2192 1.4"] = new Entry { Tw = "落雷範圍1.2\u21921.4", Cn = "落雷范围1.2\u21921.4" };
        Map["Strikes a random enemy location with lightning every 3s."] = new Entry { Tw = "ランダムな敵位置に3秒に1回落雷。", Cn = "ランダムな敌位置に3秒に1回落雷。" };
        Map["Stronger top/bottom tile APS buff"] = new Entry { Tw = "上下マス攻速強化UP", Cn = "上下マス攻速强化UP" };
        Map["Stun 2.5s"] = new Entry { Tw = "暈眩2.5秒", Cn = "暈眩2.5秒" };
        Map["Stun 3.5s"] = new Entry { Tw = "暈眩3.5秒", Cn = "暈眩3.5秒" };
        Map["Sun: {0}"] = new Entry { Tw = "太陽: {0}", Cn = "太陽: {0}" };
        Map["Survival Time"] = new Entry { Tw = "生存時間", Cn = "生存时间" };
        Map["Suspiciously Perfect Penguin"] = new Entry { Tw = "可疑的完美企鵝", Cn = "可疑的完美企鹅" };
        Map["Swarm"] = new Entry { Tw = "物量", Cn = "物量" };
        Map["Swarm Party"] = new Entry { Tw = "物量隊伍", Cn = "物量隊伍" };
        Map["Synergies"] = new Entry { Tw = "羈絆", Cn = "羈绊" };
        Map["Synergy"] = new Entry { Tw = "羈絆", Cn = "羈绊" };
        Map["Synergy  {0}"] = new Entry { Tw = "羈絆  {0}", Cn = "羈绊  {0}" };
        Map["Synergy count \u00d72"] = new Entry { Tw = "羈絆寄与 \u00d72", Cn = "羈绊寄与 \u00d72" };
        Map["Synergy Effects"] = new Entry { Tw = "羈絆効果", Cn = "羈绊効果" };
        Map["Tank specials in front, ranged in back. Enemy mix varies by phase."] = new Entry { Tw = "タンク特殊モブ前衛＋遠距離後方。区間ごとに敵構成が異なります。", Cn = "タンク特殊モブ前卫＋远距离后方。区间ごとに敌構成が異なります。" };
        Map["Tap to acquire"] = new Entry { Tw = "タップで獲得", Cn = "タップで获得" };
        Map["The full version will bring more units, synergies,\nand powerful enemies.\nStay tuned for future updates!"] = new Entry { Tw = "完整版將帶來更多單位、羈絆\n與更強大的敵人。\n敬請期待後續更新！", Cn = "完整版将带来更多单位、羁绊\n与更强大的敌人。\n敬请期待后续更新！" };
        Map["This unit can no longer be purchased."] = new Entry { Tw = "この單位はこれ以上購入できません", Cn = "この单位はこれ以上购入できません" };
        Map["This unit can no longer evolve."] = new Entry { Tw = "この單位はこれ以上進化できません", Cn = "この单位はこれ以上进化できません" };
        Map["Throws a fireball at the nearest enemy every 3s; hits deal splash damage."] = new Entry { Tw = "最も近い敵に3秒に1回火球。命中時に周囲へ追加ダメージ。", Cn = "最も近い敌に3秒に1回火球。命中时に周囲へ追加ダメージ。" };
        Map["Throws a judgment lance at the nearest enemy every 5s."] = new Entry { Tw = "最も近い敵に5秒に1回審判の槍を投げる。", Cn = "最も近い敌に5秒に1回審判の槍を投げる。" };
        Map["Throws a piercing shuriken every 3s."] = new Entry { Tw = "3秒に1回貫通手裏剣を投げる。", Cn = "3秒に1回貫通手裏剣を投げる。" };
        Map["Throws a roaming stone every 10s."] = new Entry { Tw = "10秒に1回ローミング石を投げる。", Cn = "10秒に1回ローミング石を投げる。" };
        Map["Throws rocks at the nearest enemy once every 2s."] = new Entry { Tw = "最も近い敵に2秒に1回石を投げて攻擊。", Cn = "最も近い敌に2秒に1回石を投げて攻击。" };
        Map["Throws shuriken in rapid succession {0}."] = new Entry { Tw = "敵に{0} 手裏剣を連続投擲。", Cn = "敌に{0} 手裏剣を连続投擲。" };
        Map["Thunder Sniper"] = new Entry { Tw = "雷狙撃手", Cn = "雷狙撃手" };
        Map["Tick +15% \u00b7 interval \u22128%"] = new Entry { Tw = "跳傷 +15% \u00b7 間隔 \u22128%", Cn = "跳伤 +15% \u00b7 间隔 \u22128%" };
        Map["Tier {0}/{1}"] = new Entry { Tw = "Tier {0}/{1}", Cn = "Tier {0}/{1}" };
        Map["Title Screen"] = new Entry { Tw = "タイトルへ", Cn = "タイトルへ" };
        Map["Top 5"] = new Entry { Tw = "上 5", Cn = "上 5" };
        Map["Top row (row 1)"] = new Entry { Tw = "上段行全体 (行1)", Cn = "上段行全体 (行1)" };
        Map["Top row \u00b7 attack +10%"] = new Entry { Tw = "上段 \u00b7 攻擊力 +10%", Cn = "上段 \u00b7 攻击力 +10%" };
        Map["Top Volley"] = new Entry { Tw = "上段一斉", Cn = "上段一斉" };
        Map["Traits"] = new Entry { Tw = "特性", Cn = "特性" };
        Map["Triggers a special attack {0}."] = new Entry { Tw = "{0} 特殊攻擊を発動します。", Cn = "{0} 特殊攻击を発动します。" };
        Map["Triggers execution on {1} weak enemies {0}."] = new Entry { Tw = "弱い敵{1}体に{0} 処刑の手を発動。", Cn = "弱い敌{1}体に{0} 処刑の手を発动。" };
        Map["Triple lightning \u00b7 interval \u22128%"] = new Entry { Tw = "3連落雷\u00b7周期\u22128%", Cn = "3连落雷\u00b7周期\u22128%" };
        Map["Try Again"] = new Entry { Tw = "再挑戰", Cn = "再挑战" };
        Map["Twin lance (2nd 70%) \u00b7 0.5s stun"] = new Entry { Tw = "双槍(2本目70%)\u00b7暈眩0.5秒", Cn = "双槍(2本目70%)\u00b7暈眩0.5秒" };
        Map["Twin roots (2nd 70%)"] = new Entry { Tw = "双根(2本目70%)", Cn = "双根(2本目70%)" };
        Map["Twin shot (2nd 70%) \u00b7 interval \u22126%"] = new Entry { Tw = "2連射(2発目70%)\u00b7周期\u22126%", Cn = "2连射(2発目70%)\u00b7周期\u22126%" };
        Map["Twin shot (2nd 75%)"] = new Entry { Tw = "2連射(2発目75%)", Cn = "2连射(2発目75%)" };
        Map["Unable to load party info."] = new Entry { Tw = "隊伍情報を読み込めません", Cn = "隊伍情報を読み込めません" };
        Map["Unit Awakening"] = new Entry { Tw = "單位覺醒", Cn = "单位觉醒" };
        Map["Unit Effect"] = new Entry { Tw = "單位効果", Cn = "单位効果" };
        Map["Unit Info"] = new Entry { Tw = "單位情報", Cn = "单位情報" };
        Map["Unit Roster"] = new Entry { Tw = "單位記録", Cn = "单位記録" };
        Map["Unit {0}"] = new Entry { Tw = "單位 {0}", Cn = "单位 {0}" };
        Map["Unknown Buff"] = new Entry { Tw = "不明なバフ", Cn = "不明なバフ" };
        Map["Unknown Party"] = new Entry { Tw = "不明な隊伍", Cn = "不明な隊伍" };
        Map["Unleashes a calamity pulse nearby {0}."] = new Entry { Tw = "周囲に{0} 災厄の波動を広げる。", Cn = "周囲に{0} 灾厄の波动を広げる。" };
        Map["Unlock Awakening {0}"] = new Entry { Tw = "覺醒 {0} 解放", Cn = "觉醒 {0} 解放" };
        Map["Unlock upgrades first"] = new Entry { Tw = "強化解錠後に可能", Cn = "强化解錠后に可能" };
        Map["Upgrade"] = new Entry { Tw = "強化", Cn = "强化" };
        Map["Upgrades"] = new Entry { Tw = "強化", Cn = "强化" };
        Map["Used"] = new Entry { Tw = "已使用", Cn = "已使用" };
        Map["Vertical width +20%"] = new Entry { Tw = "縦幅+20%", Cn = "縦幅+20%" };
        Map["Vine Lash"] = new Entry { Tw = "ツタ打撃", Cn = "ツタ打撃" };
        Map["Warden"] = new Entry { Tw = "守衛", Cn = "守卫" };
        Map["Width +25%"] = new Entry { Tw = "太さ+25%", Cn = "太さ+25%" };
        Map["Wind"] = new Entry { Tw = "風", Cn = "风" };
        Map["You cleared all {0} rounds!\nThank you for defending the wall to the end."] = new Entry { Tw = "你通關了全部 {0} 回合！\n感謝你守護城牆到最後。", Cn = "你通关了全部 {0} 回合！\n感谢你守护城墙到最后。" };
        Map["Your wall has fallen."] = new Entry { Tw = "你的城牆已陷落。", Cn = "你的城墙已陷落。" };
        Map["{0:0}%"] = new Entry { Tw = "{0:0}%", Cn = "{0:0}%" };
        Map["{0} active"] = new Entry { Tw = "合計 {0}件 適用中", Cn = "合计 {0}件 適用中" };
        Map["{0} medals"] = new Entry { Tw = "{0} 勲章", Cn = "{0} 勲章" };
        Map["{0} penguin(s) \u00b7 {1} adjacent aura tile(s)"] = new Entry { Tw = "企鵝{0}体 \u00b7 隣接オーラ{1}マス", Cn = "企鹅{0}体 \u00b7 隣接オーラ{1}マス" };
        Map["{0} units"] = new Entry { Tw = "{0}体", Cn = "{0}体" };
        Map["{0} | APS {1:0.0}s | Evo {2} | ATK {3}"] = new Entry { Tw = "{0} | APS {1:0.0}s | Evo {2} | ATK {3}", Cn = "{0} | APS {1:0.0}s | Evo {2} | ATK {3}" };
        Map["{0} \u2014 Barrier Pad"] = new Entry { Tw = "{0} \u2014 防禦壁床", Cn = "{0} \u2014 防禦壁床" };
        Map["{0} \u2014 Left/Right Aura"] = new Entry { Tw = "{0} \u2014 左右オーラ", Cn = "{0} \u2014 左右オーラ" };
        Map["{0} \u2014 Top/Bottom Aura"] = new Entry { Tw = "{0} \u2014 上下オーラ", Cn = "{0} \u2014 上下オーラ" };
        Map["{0}\u2605  {1}"] = new Entry { Tw = "{0}\u2605  {1}", Cn = "{0}\u2605  {1}" };
        Map["\u2014"] = new Entry { Tw = "\u2014", Cn = "\u2014" };
        Map["\u2460 Buy <color=#FFC94D>1 unit</color> in the shop  \u2192  \u2461 Deploy on the <color=#FFC94D>board</color>  \u2192  \u2462 Press <color=#FFC94D>Start Round 1</color> or wait for countdown"] = new Entry { Tw = "\u2460 在商店購買<color=#FFC94D>1名單位</color> \u2192 \u2461 部署到<color=#FFC94D>棋盘</color> \u2192 \u2462 按下<color=#FFC94D>開始第1回合</color>或等待倒數", Cn = "\u2460 在商店购买<color=#FFC94D>1名单位</color> \u2192 \u2461 部署到<color=#FFC94D>棋盘</color> \u2192 \u2462 按下<color=#FFC94D>开始第1回合</color>或等待倒数" };
        Map["\u25b6 Evolution trait unlock!"] = new Entry { Tw = "\u25b6 進化特性解鎖！", Cn = "\u25b6 进化特性解锁！" };
        Map["\u2605 Favorites"] = new Entry { Tw = "\u2605 お気に入り", Cn = "\u2605 お気に入り" };
        Map["\u2713 Unit purchased  \u2192  \u2461 Deploy freely on the <color=#FFC94D>board</color>  \u2192  \u2462 Press <color=#FFC94D>Start Round 1</color> or wait for countdown"] = new Entry { Tw = "\u2713 已購買單位 \u2192 \u2461 自由部署到<color=#FFC94D>棋盘</color> \u2192 \u2462 按下<color=#FFC94D>開始第1回合</color>或等待倒數", Cn = "\u2713 已购买单位 \u2192 \u2461 自由部署到<color=#FFC94D>棋盘</color> \u2192 \u2462 按下<color=#FFC94D>开始第1回合</color>或等待倒数" };
    }

    public static string GetTraditional(string en)
    {
        if (string.IsNullOrEmpty(en)) return en;
        return Map.TryGetValue(en, out Entry e) ? e.Tw : en;
    }

    public static string GetSimplified(string en)
    {
        if (string.IsNullOrEmpty(en)) return en;
        return Map.TryGetValue(en, out Entry e) ? e.Cn : en;
    }

    public static string ToSimplified(string zhTw)
    {
        if (string.IsNullOrEmpty(zhTw)) return zhTw;
        var sb = new StringBuilder(zhTw.Length);
        foreach (char c in zhTw) sb.Append(ConvertCharToSimplified(c));
        return sb.ToString();
    }

    static char ConvertCharToSimplified(char c) => ChineseSimplifiedChars.Convert(c);
}

static class ChineseSimplifiedChars
{
    public static char Convert(char c)
    {
        switch (c)
        {
            case '\u9ad4': return '\u4f53';
            case '\u8a2d': return '\u8bbe';
            case '\u8072': return '\u58f0';
            case '\u904a': return '\u6e38';
            case '\u6232': return '\u620f';
            case '\u8a9e': return '\u8bed';
            case '\u806f': return '\u8054';
            case '\u7d61': return '\u7edc';
            case '\u7d93': return '\u7ecf';
            case '\u9a57': return '\u9a8c';
            case '\u7d1a': return '\u7ea7';
            case '\u55ae': return '\u5355';
            case '\u7d44': return '\u7ec4';
            case '\u8207': return '\u4e0e';
            case '\u70ba': return '\u4e3a';
            case '\u6642': return '\u65f6';
            case '\u9593': return '\u95f4';
            case '\u7121': return '\u65e0';
            case '\u6575': return '\u654c';
            case '\u7372': return '\u83b7';
            case '\u8cfc': return '\u8d2d';
            case '\u8cb7': return '\u4e70';
            case '\u958b': return '\u5f00';
            case '\u95dc': return '\u5173';
            case '\u9589': return '\u95ed';
            case '\u9078': return '\u9009';
            case '\u64c7': return '\u62e9';
            case '\u9032': return '\u8fdb';
            case '\u5718': return '\u56e2';
            case '\u50ad': return '\u4f63';
            case '\u6a94': return '\u6863';
            case '\u5eab': return '\u5e93';
            case '\u986f': return '\u663e';
            case '\u756b': return '\u753b';
            case '\u8cea': return '\u8d28';
            case '\u6eff': return '\u6ee1';
            case '\u87a2': return '\u8424';
            case '\u5c08': return '\u4e13';
            case '\u5c6c': return '\u5c5e';
            case '\u8853': return '\u672f';
            case '\u8b77': return '\u62a4';
            case '\u885b': return '\u536b';
            case '\u9a0e': return '\u9a91';
            case '\u707d': return '\u707e';
            case '\u60e1': return '\u6076';
            case '\u76dc': return '\u76d7';
            case '\u8cca': return '\u8d3c';
            case '\u96fb': return '\u7535';
            case '\u51cd': return '\u51bb';
            case '\u7d50': return '\u7ed3';
            case '\u64ca': return '\u51fb';
            case '\u50b7': return '\u4f24';
            case '\u7bc4': return '\u8303';
            case '\u570d': return '\u56f4';
            case '\u9060': return '\u8fdc';
            case '\u96e2': return '\u79bb';
            case '\u5f8c': return '\u540e';
            case '\u5fa9': return '\u590d';
            case '\u52d5': return '\u52a8';
            case '\u614b': return '\u6001';
            case '\u6a19': return '\u6807';
            case '\u6e96': return '\u51c6';
            case '\u78ba': return '\u786e';
            case '\u8a8d': return '\u8ba4';
            case '\u8b58': return '\u8bc6';
            case '\u8aaa': return '\u8bf4';
            case '\u8cc7': return '\u8d44';
            case '\u8a0a': return '\u8baf';
            case '\u8f09': return '\u8f7d';
            case '\u8b80': return '\u8bfb';
            case '\u7e3d': return '\u603b';
            case '\u8a08': return '\u8ba1';
            case '\u6578': return '\u6570';
            case '\u500b': return '\u4e2a';
            case '\u7a2e': return '\u79cd';
            case '\u985e': return '\u7c7b';
            case '\u689d': return '\u6761';
            case '\u4e26': return '\u5e76';
            case '\u9084': return '\u8fd8';
            case '\u9019': return '\u8fd9';
            case '\u88e1': return '\u91cc';
            case '\u5011': return '\u4eec';
            case '\u5c0d': return '\u5bf9';
            case '\u5c07': return '\u5c06';
            case '\u5f9e': return '\u4ece';
            case '\u4f86': return '\u6765';
            case '\u767c': return '\u53d1';
            case '\u73fe': return '\u73b0';
            case '\u5be6': return '\u5b9e';
            case '\u969b': return '\u9645';
            case '\u61c9': return '\u5e94';
            case '\u8a72': return '\u8be5';
            case '\u8b8a': return '\u53d8';
            case '\u63db': return '\u6362';
            case '\u64f4': return '\u6269';
            case '\u7e8c': return '\u7eed';
            case '\u7dad': return '\u7ef4';
            case '\u9663': return '\u9635';
            case '\u71df': return '\u8425';
            case '\u5834': return '\u573a';
            case '\u7dda': return '\u7ebf';
            case '\u7db2': return '\u7f51';
            case '\u9023': return '\u8fde';
            case '\u9396': return '\u9501';
            case '\u93c8': return '\u94fe';
            case '\u5f48': return '\u5f39';
            case '\u85e5': return '\u836f';
            case '\u5291': return '\u5242';
            case '\u89ba': return '\u89c9';
            case '\u9451': return '\u9274';
            case '\u5716': return '\u56fe';
            case '\u7d46': return '\u7eca';
            case '\u76e4': return '\u76d8';
            case '\u78bc': return '\u7801';
            case '\u9304': return '\u5f55';
            case '\u8a3b': return '\u6ce8';
            case '\u518a': return '\u518c';
            case '\u5e33': return '\u5e10';
            case '\u6236': return '\u6237';
            case '\u9818': return '\u9886';
            case '\u734e': return '\u5956';
            case '\u52f5': return '\u52b1';
            case '\u5f37': return '\u5f3a';
            case '\u9802': return '\u9876';
            case '\u6b77': return '\u5386';
            case '\u7d00': return '\u7eaa';
            case '\u8a73': return '\u8be6';
            case '\u7d30': return '\u7ec6';
            case '\u984d': return '\u989d';
            case '\u5167': return '\u5185';
            case '\u88dd': return '\u88c5';
            case '\u5099': return '\u5907';
            case '\u6b04': return '\u680f';
            case '\u9ede': return '\u70b9';
            case '\u6557': return '\u8d25';
            case '\u52dd': return '\u80dc';
            case '\u9b25': return '\u6597';
            case '\u6230': return '\u6218';
            case '\u5e2b': return '\u5e08';
            case '\u7378': return '\u517d';
            case '\u5c4d': return '\u5c38';
            case '\u9f8d': return '\u9f99';
            case '\u9ce5': return '\u9e1f';
            case '\u9b5a': return '\u9c7c';
            case '\u99ac': return '\u9a6c';
            case '\u8eca': return '\u8f66';
            case '\u9580': return '\u95e8';
            case '\u9583': return '\u95ea';
            case '\u96f2': return '\u4e91';
            case '\u9727': return '\u96fe';
            case '\u9280': return '\u94f6';
            case '\u9285': return '\u94dc';
            case '\u9435': return '\u94c1';
            case '\u92fc': return '\u94a2';
            case '\u5bf6': return '\u5b9d';
            case '\u8056': return '\u5723';
            case '\u9748': return '\u7075';
            case '\u9f9c': return '\u9f9f';
            case '\u9df9': return '\u9e70';
            case '\u7345': return '\u72ee';
            case '\u8c93': return '\u732b';
            case '\u8c6c': return '\u732a';
            case '\u96de': return '\u9e21';
            case '\u9d28': return '\u9e2d';
            case '\u9be8': return '\u9cb8';
            case '\u9bca': return '\u9ca8';
            case '\u8766': return '\u867e';
            case '\u8c9d': return '\u8d1d';
            case '\u87f2': return '\u866b';
            case '\u87fb': return '\u8681';
            case '\u880d': return '\u874e';
            case '\u9cf3': return '\u51e4';
            case '\u570b': return '\u56fd';
            case '\u5b78': return '\u5b66';
            case '\u6703': return '\u4f1a';
            case '\u554f': return '\u95ee';
            case '\u984c': return '\u9898';
            case '\u982d': return '\u5934';
            case '\u81c9': return '\u8138';
            case '\u8166': return '\u8111';
            case '\u8173': return '\u811a';
            case '\u611b': return '\u7231';
            case '\u6b61': return '\u6b22';
            case '\u6a02': return '\u4e50';
            case '\u96e3': return '\u96be';
            case '\u8f15': return '\u8f7b';
            case '\u820a': return '\u65e7';
            case '\u5ee3': return '\u5e7f';
            case '\u5ee0': return '\u5382';
            case '\u5ef3': return '\u5385';
            case '\u7e23': return '\u53bf';
            case '\u9109': return '\u4e61';
            case '\u93ae': return '\u9547';
            case '\u5340': return '\u533a';
            case '\u6771': return '\u4e1c';
            case '\u8ecc': return '\u8f68';
            case '\u8a71': return '\u8bdd';
            case '\u8996': return '\u89c6';
            case '\u807d': return '\u542c';
            case '\u5beb': return '\u5199';
            case '\u5287': return '\u5267';
            case '\u9928': return '\u9986';
            case '\u6a13': return '\u697c';
            case '\u5c64': return '\u5c42';
            case '\u865f': return '\u53f7';
            case '\u9375': return '\u952e';
            case '\u6a5f': return '\u673a';
            default: return c;
        }
    }
}
